[package]
name = "openfpga-slint_pocket_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.7.1"

[build_dependencies]
slint-build = "1.7.1"