import { Palette, Sizes } from "constants.slint";
import { SelectionRing } from "selection.slint";
export component SelectionButton inherits SelectionRing {
    in property <string> title;
    out property <length> text_height <=> self.height;
    height: text.height + 2 * Sizes.focus_ring_padding;
    // This will collapse the button to be the exact width of the content
    // width: text.width + 2 * Sizes.focus_ring_padding;
    text := Text {
        x: Sizes.focus_ring_padding;
        y: Sizes.focus_ring_padding;
        text: title;
        color: Palette.font_color;
        // Center align text
        width: parent.width;
        horizontal-alignment: center;
    }

    states [
        disabled when self.disabled: {
            text.color: Palette.font_disabled_color;
        }
    ]
}

export component CheckboxButton inherits SelectionRing {
    in property <string> title;
    in property <bool> checked;
    // out property <length> text_height <=> self.height;
    height: 16px + 2 * Sizes.focus_ring_padding;
    HorizontalLayout {
        alignment: center;
        spacing: Sizes.checkbox_gap;
        Rectangle {
            width: 12px;
            height: 12px;
            y: (parent.height - self.height) / 2;
            background: checked ? white : transparent;
        }

        text := Text {
            text: title;
            y: (parent.height - Sizes.font_size) / 2;
            color: Palette.font_color;
        }
    }
}
