export global Palette {
    in-out property <color> background_color: #000000;
    in-out property <color> focus_border: #CCCCCC;
    in-out property <color> font_color: #FFFFFF;
}

export global Sizes {
    in-out property <length> focus_thickness: 2px;
    in-out property <length> focus_ring_padding: 4px;
    in-out property <length> group_gap: 8px;
    in-out property <length> checkbox_gap: 16px;
    in-out property <length> font_size: 16px;
}
